version: '3.9'

services:
  stadion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stadion
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
